import Head from "next/head";

import style from "../styles/globals.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Next App Template</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={style.main}>
        <h1>Hello Template! :)</h1>
      </main>
    </>
  );
}
